version: '3.8'

services:
  php-app:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: appdb
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
